import { images } from "@/content/images";
import type { PackageInput } from "@/lib/schema";
import { DOMESTIC_NOTE } from "./shared";

export const rajaAmpat6d5n = {
  slug: "raja-ampat-6d5n",
  region: "dalam-negeri",
  destination: "Papua Barat Daya",
  durationDays: 6,
  durationNights: 5,
  priceFrom: 16500000,
  departureFrom: "Sorong (SOQ)",
  minPax: 10,
  hotels: [
    { city: "Sorong", name: "Swiss-Belhotel Sorong", nights: 1, stars: 4 },
    { city: "Waisai", name: "Raja Ampat Dive Lodge", nights: 4, stars: 3 },
  ],
  featured: true,
  heroImage: images["raja-ampat-piaynemo"],
  gallery: [
    images["raja-ampat-gugusan"],
    images["raja-ampat-laguna"],
    images["komodo-kapal"],
  ],
  tags: ["laut", "alam", "menyelam"],
  content: {
    id: {
      title: "Raja Ampat 6 Hari 5 Malam",
      summary:
        "Enam hari di jantung Segitiga Terumbu Karang: Piaynemo, Wayag mini, Pasir Timbul, dan desa wisata Arborek — dengan ritme yang cukup lambat untuk benar-benar menikmatinya.",
      highlights: [
        "Panorama karst Piaynemo dari dek pandang di puncak tangga",
        "Snorkeling di dermaga Arborek yang ramai ikan",
        "Pasir Timbul, gundukan pasir yang hanya muncul saat air surut",
        "Mengamati burung cendrawasih merah di Pulau Gam pada pagi hari",
      ],
      itinerary: [
        {
          day: 1,
          title: "Tiba di Sorong",
          meals: ["dinner"],
          activities: [
            "Penjemputan di Bandara Domine Eduard Osok, Sorong",
            "Check-in hotel dan istirahat",
            "Pengarahan singkat perjalanan oleh tour leader",
            "Makan malam di kota Sorong",
          ],
        },
        {
          day: 2,
          title: "Sorong – Waisai – Pulau Friwen",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan dan check-out, menuju Pelabuhan Rakyat Sorong",
            "Menyeberang ke Waisai dengan kapal cepat (± 2 jam)",
            "Mengurus kartu masuk kawasan konservasi Raja Ampat",
            "Check-in penginapan, makan siang",
            "Snorkeling perdana di Friwen Wall",
            "Makan malam dan istirahat",
          ],
        },
        {
          day: 3,
          title: "Piaynemo – Telaga Bintang",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan pagi, berlayar menuju gugusan Piaynemo",
            "Menaiki 320 anak tangga ke dek pandang Piaynemo",
            "Telaga Bintang, laguna berbentuk bintang dari puncak karst",
            "Makan siang di atas kapal",
            "Snorkeling di Melissa's Garden",
            "Kembali ke penginapan, makan malam",
          ],
        },
        {
          day: 4,
          title: "Arborek – Pasir Timbul – Manta Sandy",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan pagi, berlayar ke Desa Wisata Arborek",
            "Snorkeling di dermaga Arborek dan melihat kerajinan noken",
            "Berhenti di Pasir Timbul saat air surut",
            "Makan siang di atas kapal",
            "Mengamati pari manta di Manta Sandy",
            "Kembali ke penginapan, makan malam",
          ],
        },
        {
          day: 5,
          title: "Pulau Gam – Waisai",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Berangkat sebelum matahari terbit untuk mengamati cendrawasih merah di Pulau Gam",
            "Sarapan setelah kembali dari trekking",
            "Waktu bebas berenang atau bersantai di pantai penginapan",
            "Makan siang, dilanjutkan kunjungan ke Bukit Waiwo",
            "Makan malam perpisahan bersama rombongan",
          ],
        },
        {
          day: 6,
          title: "Waisai – Sorong – Kepulangan",
          meals: ["breakfast"],
          activities: [
            "Sarapan dan check-out penginapan",
            "Kapal cepat kembali ke Sorong",
            "Belanja oleh-oleh khas Papua",
            "Pengantaran ke Bandara Domine Eduard Osok",
          ],
        },
      ],
      includes: [
        "Hotel di Sorong 1 malam dan penginapan di Waisai 4 malam (sekamar berdua)",
        "Tiket kapal cepat Sorong – Waisai pulang-pergi",
        "Sewa kapal wisata tiga hari beserta awak dan pemandu",
        "Makan sesuai program (5x makan pagi, 4x makan siang, 5x makan malam)",
        "Kartu masuk kawasan konservasi Raja Ampat",
        "Peralatan snorkeling",
        "Tour leader dan pemandu lokal",
      ],
      excludes: [
        "Tiket pesawat pulang-pergi ke Sorong",
        "Peralatan dan biaya penyelaman bersertifikat",
        "Pengeluaran pribadi dan belanja oleh-oleh",
        "Tipping untuk awak kapal dan pemandu",
        "Asuransi perjalanan",
      ],
      notes: DOMESTIC_NOTE.id,
    },
    en: {
      title: "Raja Ampat 6 Days 5 Nights",
      summary:
        "Six days at the heart of the Coral Triangle: Piaynemo, the mini Wayag, Pasir Timbul, and Arborek village — paced slowly enough to actually take it in.",
      highlights: [
        "The Piaynemo karst panorama from the viewing deck at the top of the stairs",
        "Snorkelling off Arborek jetty, thick with fish",
        "Pasir Timbul, a sandbar that only appears at low tide",
        "Watching red birds-of-paradise on Gam Island at dawn",
      ],
      itinerary: [
        {
          day: 1,
          title: "Arrival in Sorong",
          meals: ["dinner"],
          activities: [
            "Pickup at Domine Eduard Osok Airport, Sorong",
            "Hotel check-in and rest",
            "Short trip briefing from your tour leader",
            "Dinner in Sorong",
          ],
        },
        {
          day: 2,
          title: "Sorong – Waisai – Friwen Island",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast and check-out, transfer to Sorong passenger port",
            "Fast boat across to Waisai (about 2 hours)",
            "Arrange the Raja Ampat conservation entry permit",
            "Lodge check-in and lunch",
            "First snorkelling stop at Friwen Wall",
            "Dinner and rest",
          ],
        },
        {
          day: 3,
          title: "Piaynemo – Star Lagoon",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast, then sail out to the Piaynemo cluster",
            "Climb the 320 steps to the Piaynemo viewing deck",
            "Star Lagoon, seen from the karst ridge above",
            "Lunch on board",
            "Snorkelling at Melissa's Garden",
            "Back to the lodge for dinner",
          ],
        },
        {
          day: 4,
          title: "Arborek – Pasir Timbul – Manta Sandy",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast, then sail to Arborek tourism village",
            "Snorkelling at Arborek jetty and a look at the woven noken crafts",
            "A stop at Pasir Timbul while the tide is out",
            "Lunch on board",
            "Watching manta rays at Manta Sandy",
            "Back to the lodge for dinner",
          ],
        },
        {
          day: 5,
          title: "Gam Island – Waisai",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Set out before sunrise to watch red birds-of-paradise on Gam Island",
            "Breakfast after the trek",
            "Free time to swim or relax on the lodge beach",
            "Lunch, then a visit to Waiwo Hill",
            "Farewell dinner with the group",
          ],
        },
        {
          day: 6,
          title: "Waisai – Sorong – Departure",
          meals: ["breakfast"],
          activities: [
            "Breakfast and lodge check-out",
            "Fast boat back to Sorong",
            "Shopping for Papuan souvenirs",
            "Transfer to Domine Eduard Osok Airport",
          ],
        },
      ],
      includes: [
        "1 night hotel in Sorong and 4 nights lodge in Waisai (twin sharing)",
        "Return fast boat tickets Sorong – Waisai",
        "Three-day boat charter with crew and guide",
        "Meals as per programme (5 breakfasts, 4 lunches, 5 dinners)",
        "Raja Ampat conservation entry permit",
        "Snorkelling gear",
        "Tour leader and local guide",
      ],
      excludes: [
        "Return flights to Sorong",
        "Certified diving gear and dive fees",
        "Personal expenses and souvenir shopping",
        "Tipping for crew and guide",
        "Travel insurance",
      ],
      notes: DOMESTIC_NOTE.en,
    },
  },
} satisfies PackageInput;
