import { images } from "@/content/images";
import type { PackageInput } from "@/lib/schema";
import { INTERNATIONAL_NOTE } from "./shared";

export const turki9d8n = {
  slug: "turki-9d8n",
  region: "luar-negeri",
  destination: "Türkiye",
  durationDays: 9,
  durationNights: 8,
  priceFrom: 24900000,
  departureFrom: "Jakarta (CGK)",
  airline: "Turkish Airlines",
  minPax: 25,
  hotels: [
    {
      city: "Istanbul",
      name: "Ramada Encore Istanbul Bayrampasa",
      nights: 2,
      stars: 4,
    },
    { city: "Çanakkale", name: "Iris Hotel Çanakkale", nights: 1, stars: 4 },
    {
      city: "Kuşadası",
      name: "Palm Wings Beach Resort Kuşadası",
      nights: 1,
      stars: 5,
    },
    { city: "Pamukkale", name: "Colossae Thermal Hotel", nights: 1, stars: 5 },
    { city: "Konya", name: "Ramada Plaza Konya", nights: 1, stars: 5 },
    {
      city: "Kapadokya",
      name: "Perissia Hotel & Convention Center",
      nights: 2,
      stars: 5,
    },
  ],
  featured: true,
  heroImage: images["turki-cappadocia"],
  gallery: [
    images["turki-balon"],
    images["turki-istanbul"],
    images["turki-masjid"],
  ],
  tags: ["sejarah", "budaya", "alam"],
  content: {
    id: {
      title: "Türkiye 9 Hari 8 Malam",
      summary:
        "Menyeberangi dua benua dan tiga peradaban: Istanbul, reruntuhan Troya dan Efesus, teras kapur Pamukkale, lalu lanskap peri Kapadokya.",
      highlights: [
        "Hagia Sophia dan Masjid Biru yang berhadapan di Sultanahmet",
        "Kota kuno Efesus, salah satu situs Romawi paling utuh di dunia",
        "Teras kapur putih Pamukkale dan kolam air panasnya",
        "Lanskap cerobong peri Kapadokya, dengan opsi naik balon udara saat fajar",
      ],
      itinerary: [
        {
          day: 1,
          title: "Jakarta – Istanbul",
          meals: ["lunch", "dinner"],
          activities: [
            "Berkumpul di Bandara Soekarno-Hatta dan terbang bersama Turkish Airlines",
            "Tiba di Bandara Istanbul, proses imigrasi, dan bertemu pemandu lokal",
            "Makan siang di kawasan Eminönü",
            "Menyusuri Grand Bazaar dengan lebih dari 4.000 kios",
            "Makan malam dan check-in hotel",
          ],
        },
        {
          day: 2,
          title: "Istanbul: Sultanahmet – Selat Bosphorus",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan di hotel",
            "Hagia Sophia, Masjid Biru, dan Hipodrom di alun-alun Sultanahmet",
            "Istana Topkapi dan koleksi peninggalan sucinya",
            "Makan siang, dilanjutkan pelayaran di Selat Bosphorus",
            "Spice Bazaar untuk mencicipi manisan Turki",
            "Makan malam dan kembali ke hotel",
          ],
        },
        {
          day: 3,
          title: "Istanbul – Çanakkale",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan dan check-out hotel",
            "Perjalanan menuju Çanakkale menyeberangi Laut Marmara",
            "Makan siang di Bursa dengan iskender kebab",
            "Situs arkeologi Troya dan replika kuda kayunya",
            "Check-in hotel di Çanakkale, makan malam",
          ],
        },
        {
          day: 4,
          title: "Çanakkale – Pergamon – Kuşadası",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan dan check-out hotel",
            "Akropolis Pergamon dengan teater tercuram di dunia kuno",
            "Makan siang di perjalanan",
            "Kunjungan ke pusat kulit dan wol Turki",
            "Check-in resor tepi pantai di Kuşadası, makan malam",
          ],
        },
        {
          day: 5,
          title: "Kuşadası – Efesus – Pamukkale",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan dan check-out hotel",
            "Kota kuno Efesus: Perpustakaan Celsus, teater besar, dan Jalan Marmer",
            "Rumah Bunda Maria di Bukit Bulbul",
            "Makan siang, dilanjutkan perjalanan menuju Pamukkale",
            "Check-in hotel termal, makan malam, dan berendam air panas",
          ],
        },
        {
          day: 6,
          title: "Pamukkale – Konya",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan dan check-out hotel",
            "Teras kapur putih Pamukkale dan kota kuno Hierapolis",
            "Makan siang, dilanjutkan perjalanan panjang menuju Konya",
            "Berhenti di Danau Egirdir untuk meregangkan kaki",
            "Check-in hotel di Konya, makan malam",
          ],
        },
        {
          day: 7,
          title: "Konya – Kapadokya",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Sarapan dan check-out hotel",
            "Museum Mevlana, makam Jalaluddin Rumi",
            "Berhenti di Sultanhani Caravanserai, persinggahan Jalur Sutra abad ke-13",
            "Makan siang di perjalanan",
            "Tiba di Kapadokya, check-in hotel, makan malam diiringi tarian sema",
          ],
        },
        {
          day: 8,
          title: "Kapadokya",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Balon udara saat fajar (opsional, dipesan terpisah)",
            "Sarapan di hotel",
            "Kota bawah tanah Kaymakli dan Lembah Devrent",
            "Makan siang, dilanjutkan Museum Terbuka Göreme",
            "Bengkel keramik Avanos di tepi Sungai Kizilirmak",
            "Makan malam perpisahan di hotel",
          ],
        },
        {
          day: 9,
          title: "Kapadokya – Istanbul – Jakarta",
          meals: ["breakfast"],
          activities: [
            "Sarapan dan check-out hotel",
            "Pengantaran ke Bandara Kayseri untuk penerbangan domestik ke Istanbul",
            "Transit di Bandara Istanbul",
            "Penerbangan kembali ke Jakarta",
          ],
        },
      ],
      includes: [
        "Tiket pesawat internasional pulang-pergi dan penerbangan domestik Kayseri – Istanbul",
        "Hotel bintang 4–5 selama 8 malam (sekamar berdua)",
        "Makan sesuai program (8x makan pagi, 8x makan siang, 8x makan malam)",
        "Bus pariwisata ber-AC selama di Türkiye",
        "Tiket masuk seluruh objek wisata dalam itinerary",
        "Pelayaran Selat Bosphorus dan pertunjukan tarian sema",
        "Tour leader dari Indonesia dan pemandu lokal berbahasa Indonesia",
      ],
      excludes: [
        "Paspor dengan masa berlaku minimal 6 bulan",
        "Balon udara Kapadokya (± USD 250 per orang, dipesan terpisah)",
        "Pengeluaran pribadi, laundry, dan minuman di luar program",
        "Tipping untuk pemandu dan sopir sebesar USD 60 per orang",
        "Asuransi perjalanan dan kelebihan bagasi",
      ],
      notes:
        "Warga negara Indonesia bebas visa untuk kunjungan wisata ke Türkiye hingga 30 hari. Penerbangan balon udara sangat bergantung pada cuaca dan dapat dibatalkan otoritas setempat; bila batal, biayanya dikembalikan penuh. " +
        INTERNATIONAL_NOTE.id,
    },
    en: {
      title: "Türkiye 9 Days 8 Nights",
      summary:
        "Two continents and three civilisations: Istanbul, the ruins of Troy and Ephesus, the limestone terraces of Pamukkale, and the fairy chimneys of Cappadocia.",
      highlights: [
        "Hagia Sophia and the Blue Mosque facing each other in Sultanahmet",
        "Ancient Ephesus, one of the best-preserved Roman sites anywhere",
        "The white limestone terraces of Pamukkale and its thermal pools",
        "Cappadocia's fairy-chimney landscape, with an optional dawn balloon flight",
      ],
      itinerary: [
        {
          day: 1,
          title: "Jakarta – Istanbul",
          meals: ["lunch", "dinner"],
          activities: [
            "Meet at Soekarno-Hatta Airport and fly with Turkish Airlines",
            "Arrive at Istanbul Airport, clear immigration, and meet the local guide",
            "Lunch in the Eminönü district",
            "A walk through the Grand Bazaar and its 4,000-plus stalls",
            "Dinner and hotel check-in",
          ],
        },
        {
          day: 2,
          title: "Istanbul: Sultanahmet – the Bosphorus",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast at the hotel",
            "Hagia Sophia, the Blue Mosque, and the Hippodrome on Sultanahmet square",
            "Topkapi Palace and its collection of sacred relics",
            "Lunch, then a Bosphorus strait cruise",
            "The Spice Bazaar for a Turkish delight tasting",
            "Dinner, then back to the hotel",
          ],
        },
        {
          day: 3,
          title: "Istanbul – Çanakkale",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast and hotel check-out",
            "Drive to Çanakkale, crossing the Sea of Marmara",
            "Iskender kebab lunch in Bursa",
            "The archaeological site of Troy and its replica wooden horse",
            "Hotel check-in in Çanakkale and dinner",
          ],
        },
        {
          day: 4,
          title: "Çanakkale – Pergamon – Kuşadası",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast and hotel check-out",
            "The Pergamon acropolis, with the steepest theatre of the ancient world",
            "Lunch en route",
            "A visit to a Turkish leather and wool centre",
            "Check in to a beachfront resort in Kuşadası and have dinner",
          ],
        },
        {
          day: 5,
          title: "Kuşadası – Ephesus – Pamukkale",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast and hotel check-out",
            "Ancient Ephesus: the Library of Celsus, the great theatre, and Marble Street",
            "The House of the Virgin Mary on Bulbul Hill",
            "Lunch, then the drive to Pamukkale",
            "Check in to a thermal hotel, dinner, and a hot spring soak",
          ],
        },
        {
          day: 6,
          title: "Pamukkale – Konya",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast and hotel check-out",
            "The white terraces of Pamukkale and the ancient city of Hierapolis",
            "Lunch, then the long drive to Konya",
            "A leg-stretch stop at Lake Egirdir",
            "Hotel check-in in Konya and dinner",
          ],
        },
        {
          day: 7,
          title: "Konya – Cappadocia",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Breakfast and hotel check-out",
            "The Mevlana Museum, resting place of Jalaluddin Rumi",
            "A stop at Sultanhani Caravanserai, a 13th-century Silk Road inn",
            "Lunch en route",
            "Arrive in Cappadocia, check in, and have dinner with a sema dance performance",
          ],
        },
        {
          day: 8,
          title: "Cappadocia",
          meals: ["breakfast", "lunch", "dinner"],
          activities: [
            "Dawn hot-air balloon flight (optional, booked separately)",
            "Breakfast at the hotel",
            "The Kaymakli underground city and Devrent Valley",
            "Lunch, then the Göreme Open Air Museum",
            "Avanos pottery workshops on the Kizilirmak river",
            "Farewell dinner at the hotel",
          ],
        },
        {
          day: 9,
          title: "Cappadocia – Istanbul – Jakarta",
          meals: ["breakfast"],
          activities: [
            "Breakfast and hotel check-out",
            "Transfer to Kayseri Airport for the domestic flight to Istanbul",
            "Transit at Istanbul Airport",
            "Flight home to Jakarta",
          ],
        },
      ],
      includes: [
        "Return international flights and the domestic Kayseri – Istanbul leg",
        "4–5 star hotels for 8 nights (twin sharing)",
        "Meals as per programme (8 breakfasts, 8 lunches, 8 dinners)",
        "Air-conditioned coach throughout Türkiye",
        "Entrance tickets to every attraction in the itinerary",
        "Bosphorus cruise and the sema dance performance",
        "Tour leader from Indonesia and a local guide",
      ],
      excludes: [
        "A passport valid for at least 6 months",
        "The Cappadocia balloon flight (about USD 250 per person, booked separately)",
        "Personal expenses, laundry, and drinks outside the programme",
        "Tipping for guide and driver of USD 60 per person",
        "Travel insurance and excess baggage",
      ],
      notes:
        "Indonesian passport holders do not need a visa for tourist visits to Türkiye of up to 30 days. Balloon flights depend heavily on the weather and can be cancelled by the local authority; if that happens the fee is refunded in full. " +
        INTERNATIONAL_NOTE.en,
    },
  },
} satisfies PackageInput;
